config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products, path: "/"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord

  validates :name, presence: true
  has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  
  ORDER_BY = {
    recent: "created_at DESC",
    oldest: "created_at ASC",
    expensive: "price DESC",
    cheap: "price ASC"
  }

  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B'
  }
  
  has_one_attached :photo
  
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  around_action :switch_locale

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end

  private

  def locale_from_header
    request.env["HTTP_ACCEPT_LANGUAGE"]&.scan(/^[a-z]{2}/)&.first
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all.order(name: :asc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: t('activerecord.successful.messages.created', :model => @category.class.model_name.human) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: t('activerecord.successful.messages.updated', :model => @category.class.model_name.human) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: t('activerecord.successful.messages.destroyed', :model => @category.class.model_name.human) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.all.load_async
    @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index).load_async, items: 12)
  end

  def show
    product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: t(".created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    product
  end

  def update    
    if product.update(product_params)
      redirect_to products_path, notice: t(".updated")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    product.destroy

    redirect_to products_path, notice: t(".destroyed"), status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end

  def product_params_index
    params.permit(:category_id, :min_price, :max_price, :query_text, :order_by)
  end

  def product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <%= category.name %>
  <%= link_to t('common.edit'), edit_category_path(category) %>
  <%= link_to t('common.destroy'), category_path(category), data: {
  turbo_method: :delete,
  turbo_confirm: t('common.confirm_action')
}%>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, t('common.form_errors.error')) %> <%= t('common.form_errors.error_full') %></h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, t('.name'), style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to t('.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>

<%= render partial: 'category', collection: @categories %>

<%= link_to t('.add_category'), new_category_path %>

app/views/categories/new.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sellit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flash"%>
    <%= render "shared/header"%>
    <%= yield %>
  </body>
</html>

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: "category" do%>
<%= category.name %> 
<%end%>

app/views/products/_form.html.erb
<%= form_with model: @product do |f| %>
  <% if @product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@product.errors.count, t('common.form_errors.error')) %> <%= t('common.form_errors.error_full')%></h2>

      <ul>
        <% @product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :title, t(".title") %>
    <%= f.text_field :title%>
  </div>
  <div>
    <%= f.label :description, t(".description") %>
    <%= f.text_area :description%>
  </div>
  <div>
    <%= f.label :price, t(".price") %>
    <%= f.number_field :price%>
  </div>
  <div>
    <%= f.label :category_id, t(".category") %>
    <%= f.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
  </div>
  <div>
    <%= f.label :photo, t(".photo")%>
    <%= f.file_field :photo%>
  </div>


  <%=f.submit%>
<%end%>

app/views/products/_product.html.erb
<%= link_to product_path(product.id), class: "product", "data-turbo-frame": "_top" do%>
  <%= image_tag product.photo.attached? ? product.photo : "default.png", width: 200%>
  <h2><%= product.title %></h2>
  <span><%= product.price%>$</span>
<% end %>

app/views/products/edit.html.erb
<h1>Editar Producto</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do %>

  <h1><%= t('.title') %></h1>

  <%= form_with url: products_path, method: :get do |form| %>
    <%= form.text_field :query_text, placeholder: t('.query_text'), onChange: 'this.form.requestSubmit()', value: params[:query_text] %>

    <%= form.number_field :min_price, placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()', value: params[:min_price] %>
    <%= form.number_field :max_price, placeholder: t('.max_price'), onChange: 'this.form.requestSubmit()', value: params[:max_price] %>
    <%= hidden_field_tag :category_id, params[:category_id] %>

    <%= form.select :order_by, options_for_select(Product::ORDER_BY.keys.map { |order| [t(".#{order}"), order] }, params[:order_by]), {}, { onChange: 'this.form.requestSubmit()' } %>
  <% end %>

  <%= link_to t('.all'), products_path %>

  <%= render partial: 'category', collection: @categories %>
  <br>
  <%= turbo_frame_tag "products-#{@pagy.page}", class: "products" do %>
    <%= render partial: 'product', collection: @products %>
    <%= turbo_frame_tag "products-#{@pagy.next}", class: "products", src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/show.html.erb
<%= image_tag @product.photo.attached? ? @product.photo : "default.png", width: 200%>
<h1 class="title"><%= @product.title%></h1>

<p class="description"><%= @product.description%></p>

<span class="price"><%= @product.price%>$</span>

<%= link_to t('common.edit'), edit_product_path(@product)%>
<%= link_to t('common.destroy'), product_path(@product), data: {
  turbo_method: :delete,
  turbo_confirm: t('common.confirm_action')
}%>

app/views/shared/_flash.html.erb
<%= notice %>

<%= alert %>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
  <h1>Sellit</h1>
<% end %>
<%= link_to t('.add_product'), new_product_path %>
<%= link_to t('.categories'), categories_path %>
<hr>